# Common vars
availability_zone: melbourne-qh2-uom
project_working_directory: /home/xmkz/ccc/COMP90024-A2/ansible

# Volume
volumes:
  - vol_name: vol-1-1
    vol_size: 20
  - vol_name: vol-1-2
    vol_size: 40
  - vol_name: vol-2-1
    vol_size: 20
  - vol_name: vol-2-2
    vol_size: 40
  - vol_name: vol-3-1
    vol_size: 20
  - vol_name: vol-3-2
    vol_size: 40
  - vol_name: vol-4-1
    vol_size: 10
  - vol_name: vol-4-2
    vol_size: 10

# Security group
security_groups:
  - name: ssh_group55
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http_group55
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: fauxton_ui
    description: "Security group for couch DB fauxton UI access"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: nginx
    description: "Security group for nginx access"
    protocol: tcp
    port_range_min: 10000
    port_range_max: 10000
    remote_ip_prefix: 0.0.0.0/0

# Security group for couch db
sg_couchdb_name: couchdb
sg_couchdb_description: "Security group for couch DB"
sg_couchdb_protocol: tcp
sg_couchdb_remote_group: '{{ sg_couchdb_name }}'
couchdb_port_range:
  - port_range_min: 5984
    port_range_max: 5984
  - port_range_min: 4369
    port_range_max: 4369
  - port_range_min: 9100
    port_range_max: 9200

# Security group for docker swarm
sg_swarm_name: docker_swarm
sg_swarm_description: "Security group for docker swarm"
sg_swarm_remote_group: '{{ sg_swarm_name }}'
swarm_port_range:
  - protocol: tcp
    port_range_min: 2377
    port_range_max: 2377
  - protocol: tcp
    port_range_min: 7946
    port_range_max: 7946
  - protocol: udp
    port_range_min: 7946
    port_range_max: 7946
  - protocol: udp
    port_range_min: 4789
    port_range_max: 4789

# Instance
instances:
  - name: instance1
    volumes: ['vol-1-1', 'vol-1-2']
  - name: instance2
    volumes: ['vol-2-1', 'vol-2-2']
  - name: instance3
    volumes: ['vol-3-1', 'vol-3-2']
  - name: instance4
    volumes: ['vol-4-1', 'vol-4-2']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: group55-key
instance_flavor: uom.mse.2c9g