---
- name: Deploy web app
  docker_swarm_service:
    name: webapp
    image: emostudio/webapp
    publish:
      - published_port: 8080
        target_port: 8080
    replicas: 3

- name: Deploy couchdb api
  docker_swarm_service:
    name: couchdb_api
    image: emostudio/couchdb_api
    publish:
      - published_port: 5000
        target_port: 5000
    replicas: 1

- name: Deploy tweets harvester
  docker_swarm_service:
    name: harvester
    image: emostudio/harvester
    publish:
      - published_port: 5001
        target_port: 5001
    replicas: 1

- name: Deploy machine learning server
  docker_swarm_service:
    name: machine_learning
    image: emostudio/machine_learning
    publish:
      - published_port: 5002
        target_port: 5002
    replicas: 1