---
# Create a security group
- name: Create a security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'

- name: Create a list of security group names
  set_fact:
    sg_names: '{{ sg_names|default([]) + [ item.name ] }}'
  loop: '{{ security_groups }}'

# Create a security group for couch db
- name: Create a security group
  os_security_group:
    name: '{{ sg_couchdb_name }}'
    description: '{{ sg_couchdb_description }}'
    state: present

- name: Add couchdb to the list of security group names
  set_fact:
    sg_names: '{{ sg_names + [ sg_couchdb_name ] }}'

# Create a security group for docker swarm
- name: Create a security group
  os_security_group:
    name: '{{ sg_swarm_name }}'
    description: '{{ sg_swarm_description }}'
    state: present

- name: Add couchdb to the list of security group names
  set_fact:
    sg_names: '{{ sg_names + [ sg_swarm_name ] }}'

- debug:
    msg: "Security group(s) {{ sg_names }} have been created."

# Create security group rules
- name: Create security group rules
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: present
  loop: '{{ security_groups }}'

# Create security group rules for couchdb
- name: Create security group rules
  os_security_group_rule:
    security_group: '{{ sg_couchdb_name }}'
    protocol: '{{ sg_couchdb_protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_group: '{{ sg_couchdb_remote_group }}'
    state: present
  loop: '{{ couchdb_port_range }}'

# Create security group rules for docker swarm
- name: Create security group rules
  os_security_group_rule:
    security_group: '{{ sg_swarm_name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_group: '{{ sg_swarm_remote_group }}'
    state: present
  loop: '{{ swarm_port_range }}'